bootstrap_servers: ["localhost:9092"]
# For streamable mode: 'sanierungsdata', 'mieterstromdata', 'electro-mobility' 
dataset_topic: {"mieterstromdata": "energy-data", "sanierungsdata": 'sanierung-data'}
streaming: true
delay: 0.3