bootstrap_servers: ["localhost:9092"]
# For streamable mode: 'sanierungsdata', 'mieterstromdata', 'electro-mobility' 
dataset_topic: {"electro-mobility" : "electromobility"}
streaming: true
delay: 0.3