name: Format

on: [ pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3 # v2 minimum required
      - name: Lint Codebase
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          JAVA_FILE_NAME: checkstyle_checks.xml